# Generated by Django 5.2.15 on 2026-06-25 21:33

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('s3_key', models.CharField(max_length=512)),
                ('size_bytes', models.BigIntegerField()),
                ('occurrence_count', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'chunks',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('upload_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_chunks', models.IntegerField(default=0)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('duration_s', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'videos',
                'indexes': [models.Index(fields=['user_id'], name='idx_videos_user_id')],
            },
        ),
        migrations.CreateModel(
            name='VideoChunk',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('chunk_index', models.IntegerField()),
                ('chunk', models.ForeignKey(db_column='chunk_id', on_delete=django.db.models.deletion.PROTECT, related_name='video_assignments', to='videos.chunk')),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='videos.video')),
            ],
            options={
                'db_table': 'video_chunks',
                'ordering': ['chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('video', 'chunk_index'), name='uidx_video_chunk_index')],
            },
        ),
        migrations.CreateModel(
            name='VideoFormat',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('resolution', models.CharField(max_length=20)),
                ('s3_key', models.CharField(max_length=512)),
                ('codec', models.CharField(default='h264', max_length=20)),
                ('bitrate_kbps', models.IntegerField(blank=True, null=True)),
                ('ready', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(db_column='video_id', on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='videos.video')),
            ],
            options={
                'db_table': 'video_formats',
                'indexes': [models.Index(fields=['s3_key'], name='idx_formats_s3_key')],
            },
        ),
    ]
