# Generated by Django 5.2.15 on 2026-08-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_video_composite_hash_video_hls_master_s3_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('queued', 'Queued')], db_index=True, default='pending', max_length=20),
        ),
    ]
