# Generated by Django 5.2.15 on 2026-08-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_alter_video_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='videoformat',
            constraint=models.UniqueConstraint(fields=('video', 'resolution'), name='uidx_video_resolution'),
        ),
    ]
